project_id = "fketquljzcnskqazwwog"

[functions.create-professional-access]
verify_jwt = false

[functions.create-salon]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.save-setup-config]
verify_jwt = false
